### ISSUE TITLE
Server needs changing

### ISSUE THREAD

**Issue by ComedyTomedy** [Ru5ty0ne/popcorn_cli#1]
`popcorn-ru.tk` is down, presumably due to the war. The graphical Popcorn client now appears to use a comma-separated list of alternate servers, popcorn-time.ga, movies-api.tk, movies-api.ga, plus others that I can't see.

Quick fix would be to change to one of these. A better fix long-term might be to have (say) a queue of servers and push any that fail to the back, especially if popcorn_cli saves state somewhere.

```
$ popcorn movie tt0485947
Error: error decoding response body: expected value at line 1 column 1

Caused by:
    expected value at line 1 column 1
```

But

```
$ popcorn -d https://popcorn-time.ga movie tt0485947

Mr. Nobody

Available resolutions: ["480p", "1080p"]
```

**Comment by perryaa** [comment]
While my ru.tk link for TV shows is no good now, the Movie .MX link works fine. As the situation evolves in Ukraine, continue to up links for movies and TV shows in discussion as an FYI

**Comment by Ru5ty0ne** [comment]
Thank you for pointing out the issue. I made a quick fix and uploaded it to crates.io
@[ComedyTomedy](https://github.com/ComedyTomedy) sorry for not merging your PR
Since I'm russian I want to apologize on behalf of sane russian people.

**Comment by ComedyTomedy** [comment]
Thanks ❤️ I think many of us are embarrassed by our governments these days!
